name: 16 - Working with Environments
run-name: "16 - Working with Environments | Env: ${{ inputs.target-env }}"

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: 'Select the target environment'
        required: true
        default: "staging"

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'Default env value' }}  
    steps:
      - name: "Print environment and variable"
        run: echo "Env variable:" ${{ env.my-env-value }}

  

